# Numpy  ( 10-10-19 thursday )

In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print(b-a)

[5 5 5 5 5]


In [3]:
b+a

array([ 7,  9, 11, 13, 15])

In [4]:
b/a

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [5]:
b%a

array([0, 1, 2, 1, 0], dtype=int32)

In [6]:
b//a

array([6, 3, 2, 2, 2], dtype=int32)

In [7]:
a*b

array([ 6, 14, 24, 36, 50])

In [8]:
a**b

array([      1,     128,    6561,  262144, 9765625], dtype=int32)

#### INDEXING

In [9]:
a[0]

1

In [10]:
a[:10]  # print start to end bcoz till 10th index , we have only till 4th index  so print it

array([1, 2, 3, 4, 5])

In [11]:
a[10:]  # out last index in 4, we want from 10 so no elemnt , so print empty array

array([], dtype=int32)

In [12]:
a[-1]

5

In [13]:
a[-1:]

array([5])

In [14]:
a[-1:-3]  # bcoz by default increment is 1

array([], dtype=int32)

In [15]:
a[-1:-4:-1]  # decrease indexing so it print

array([5, 4, 3])

In [16]:
a[-1:5]

array([5])

In [17]:
a==b

array([False, False, False, False, False])

In [18]:
a!=b

array([ True,  True,  True,  True,  True])

In [19]:
a<b

array([ True,  True,  True,  True,  True])

In [20]:
a>b

array([False, False, False, False, False])

In [21]:
x=np.array([])   # by default data type is float
x

array([], dtype=float64)

In [36]:
x[0]=1

In [37]:
a.shape ### why only 5

(2, 3)

In [38]:
x=np.array(10)    # we have not given
x

array(10)

In [39]:
x.ndim

0

In [40]:
x.shape

()

In [41]:
x=np.array([10])
x

array([10])

In [28]:
x.ndim    # 0 dimension means those r scalar

1

In [29]:
x.shape   #

(1,)

In [30]:
x.dtype   # store in a bit

dtype('int32')

### SCALAR

In [31]:
import matplotlib.pyplot as plt

In [32]:
a=np.array(((10,20,30),(4,5,6)))   # () for functions
b=np.array(10)   # 0 dimension bcoz its scalar
a.ndim
 

2

In [33]:
b.ndim

0

In [42]:
c=np.array(10,20)  #only one element more than 1 it will give error
c

TypeError: data type not understood

In [ ]:
print(a.dtype)

In [ ]:
a.itemsize

In [ ]:
b=np.array([10,20,30,40,50])     # always 4 bit bcoz its integer type for boolean 1, float 8,complex 128, string 64
b.itemsize

In [ ]:
c=np.array([1,"hi",2.0,2J,True,"hi"])    # type proority from string, complex , float , int , boolean
c.dtype                                          # u11 means 12 its caary 1  more than 1 string

In [ ]:
b.size

In [ ]:
b.data # find the memory adress

In [ ]:
d=np.array([[10,20],2.2,"ji"])     # O(aoo) means mixed value array or OBJECT
d.dtype 

In [ ]:
a=np.array([10,20])
print(a.astype(float))    # astype used for data type conversion
print(a.astype(complex))

### vector

In [43]:
c=np.array([6,7,8])
c

array([6, 7, 8])

In [44]:
np.ndim(c)

1

In [45]:
np.shape(c)    # when no columns r there this woill show only row

(3,)

In [46]:
d=np.array({1,2,3})   # when u take any value in dictionary it will take as a OBJECT
print(d.dtype,d)    # dtype (O) means object

object {1, 2, 3}


In [47]:
e=np.array(10)    # true
e=np.array(10,int) # true
# e=np.array(10,20,30) # Wrong, u can not give more than one value to 1 variable so its wrong n given error
e

array(10)

In [48]:
b=np.array([(1,2,3.0),(4,5,6)])
b.dtype

dtype('float64')

In [49]:
b.ndim

2

In [50]:
b.shape

(2, 3)

In [51]:
b.size

6

In [52]:
b.itemsize

8

In [53]:
b.dtype

dtype('float64')

In [54]:
d=np.array([[1,2],[3,4]],dtype=np.complex)
d

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [55]:
d.itemsize

16

In [56]:
a=np.array([True])
a.itemsize

1

In [57]:
import numpy as np

In [58]:
a3d=np.array([[[1,2],[3,4],[5,6]]])
a3d

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [59]:
a3d.itemsize

4

In [60]:
a3d.ndim

3

In [61]:
a3d.shape    # 2 means column ,3 means rows, 1 means no of arrays

(1, 3, 2)

## ****************** 14-10-19  MONDAY ***********************

### TRANSPOSITION

In [62]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [63]:
at=a.T
at

array([[1, 3, 5],
       [2, 4, 6]])

In [64]:
a.shape

(3, 2)

In [65]:
at.shape

(2, 3)

In [66]:
b=np.matrix([[1,2],[3,4],[5,6]])
b

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [67]:
bt=b.T
bt

matrix([[1, 3, 5],
        [2, 4, 6]])

In [68]:
b.shape

(3, 2)

In [69]:
bt.shape

(2, 3)

In [70]:
a.ndim

2

In [71]:
c=np.array([[[1,2],[3,4],[5,6]]])
c

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [72]:
ct=c.T
ct

array([[[1],
        [3],
        [5]],

       [[2],
        [4],
        [6]]])

In [73]:
c.shape

(1, 3, 2)

In [74]:
ct.shape

(2, 3, 1)

In [75]:
c.ndim

3

### Addition

In [76]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [77]:
b=np.array([[2,5],[7,4],[4,3]])
b

array([[2, 5],
       [7, 4],
       [4, 3]])

In [78]:
c=a+b
c

array([[ 3,  7],
       [10,  8],
       [ 9,  9]])

In [79]:
a+4

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [80]:
x=np.array([1,2])   # add to each row
c=a+x
c

array([[2, 4],
       [4, 6],
       [6, 8]])

### broadcasting

In [81]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [82]:
b=np.array([[2],[4],[6]])   # this will add to each row elements ( all same not like [2,5],[4],[6] we got error)
b

array([[2],
       [4],
       [6]])

In [83]:
c=a+b
c

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [ ]:
import seaborn as sns

## *********  15-10-19 (Tuesday)

### trace

In [84]:
import numpy as np
a=np.array([[2,9,8],[4,7,1],[8,2,5]])

In [85]:
a

array([[2, 9, 8],
       [4, 7, 1],
       [8, 2, 5]])

In [86]:
a_tr=np.trace(a)
a_tr

14

In [87]:
a=np.array([[1,2,3],[4,5,6]])
a.trace()

6

In [88]:
np.linalg.norm(a)  # the frobenius norm of a is 17.54....

9.539392014169456

In [89]:
np.sqrt(np.trace(a.dot(a.T)))

9.539392014169456

In [90]:
a=np.array([[4,12],[7,6]])
b=np.array([[1,-3],[4,3]])
c=np.array([[6,6],[2,5]])

np.trace(a.dot(b).dot(c))

531

In [91]:
a.dot(b).dot(c)

array([[360, 432],
       [180, 171]])

In [92]:
b.dot(c).dot(a)

array([[-63, -54],
       [393, 594]])

In [93]:
c.dot(a).dot(b)

array([[498, 126],
       [259,  33]])

# universal function of numpy

In [2]:
a=np.random.random((3,3))
a

array([[0.05204044, 0.17261151, 0.38435446],
       [0.85144384, 0.92268902, 0.07802514],
       [0.72287886, 0.58870547, 0.40709127]])

In [3]:
print(a.sum())

4.179840015970179


In [4]:
print(a.sum(axis=0), "#sum of each columns")

[1.62636314 1.68400601 0.86947087] #sum of each columns


In [5]:
print(a.sum(axis=1),"sum of each rows")

[0.60900641 1.852158   1.7186756 ] sum of each rows


In [6]:
print(a.min())

0.05204044065945146


In [7]:
print(a.min(axis=0))

[0.05204044 0.17261151 0.07802514]


In [8]:
print(a.min(axis=1))   # for 3d array axis=2, 

[0.05204044 0.07802514 0.40709127]


In [9]:
print(a.max())

0.9226890180825824


In [10]:
print(a.max(axis=0))

[0.85144384 0.92268902 0.40709127]


In [11]:
print(a.max(axis=1))

[0.38435446 0.92268902 0.72287886]


### Cumltive sum

In [12]:
b=np.array([[1,2,5],[3,4,6],[8,9,10]])
b

array([[ 1,  2,  5],
       [ 3,  4,  6],
       [ 8,  9, 10]])

In [13]:
b.cumsum()

array([ 1,  3,  8, 11, 15, 21, 29, 38, 48], dtype=int32)

In [14]:
b.cumsum(axis=0)   # column vise

array([[ 1,  2,  5],
       [ 4,  6, 11],
       [12, 15, 21]], dtype=int32)

In [15]:
b.cumsum(axis=1)   # row wise

array([[ 1,  3,  8],
       [ 3,  7, 13],
       [ 8, 17, 27]], dtype=int32)

In [16]:
b.cumprod()

array([     1,      2,     10,     30,    120,    720,   5760,  51840,
       518400], dtype=int32)

In [17]:
b.cumprod(axis=0)

array([[  1,   2,   5],
       [  3,   8,  30],
       [ 24,  72, 300]], dtype=int32)

In [18]:
b.cumprod(axis=1)   # int32 bydefault data type if u r not given any data type

array([[  1,   2,  10],
       [  3,  12,  72],
       [  8,  72, 720]], dtype=int32)

In [ ]:
b=np.arange(3)
print(np.exp(b))

In [ ]:
import matplotlib.pyplot as plt
from matplotlib import style
style.use('bmh')
c=np.arange(-5.,5,0.1)
print("size of c",c.size)
# c
y=np.exp(c)
y1=np.random.random(c.size)
y2=y1+y
#plt.scatter(c,y,color='y')
plt.plot(y2,'g')
plt.grid(True,color='r')
plt.xlabel('x axis')
plt.ylabel('y axis')
plt.title(" DATA PLOTING")
# plt.bar(c,y)

In [19]:
a=np.array([10,15,20])
b=np.array([5,15,20])

In [20]:
a+b

array([15, 30, 40])

In [21]:
np.add(a,b)

array([15, 30, 40])

In [22]:
a.shape

(3,)

In [23]:
b.shape

(3,)

In [24]:
np.sqrt(a)

array([3.16227766, 3.87298335, 4.47213595])

In [25]:
np.sqrt(b)

array([2.23606798, 3.87298335, 4.47213595])

### ALL, ANY

In [26]:
np.all([[True,False],[True,True]])

False

In [27]:
np.all([[True,True],[True,True]])

True

In [28]:
np.any([[True,False],[True,True]])

True

In [29]:
np.any([False,False])

False

In [30]:
np.any([np.nan,2,4])

True

In [31]:
np.nan

nan

In [32]:
np.nan+100

nan

In [33]:
np.nan-500

nan

In [34]:
a=np.array([10,20,3,40,50,60])
b=np.nan
a+b    # add or subtact any value to "None" we got "None"

array([nan, nan, nan, nan, nan, nan])

In [35]:
###  APPLY_along_axis

In [36]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [37]:
np.apply_along_axis(np.diag,0,a)

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [ ]:
np.apply_along_axis(np.diag,1,a)   # seprate each row bcoz axis=1    # axis 1 and -2 are same

In [ ]:
 np.apply_along_axis(np.diag,-1,a)   # seprate each row bcoz axis=-1 means equal to 2 =diagonal

In [ ]:
np.apply_along_axis(np.diag,2,a)   # seprate each row bcoz axis=2 means doagonal

In [ ]:
np.apply_along_axis(np.diag,-2,a)   # seprate each row bcoz axis=-2 equal to axis=1

In [38]:
a=np.arange(6).reshape(2,3)+10
a

array([[10, 11, 12],
       [13, 14, 15]])

In [39]:
np.argmin(a) ### 10 element

0

In [40]:
np.argmax(a)

5

In [41]:
np.argsort(a)

array([[0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [42]:
b=np.array([[[10,5,25],[22,6,18]]])
b

array([[[10,  5, 25],
        [22,  6, 18]]])

In [43]:
np.argsort(b)

array([[[1, 0, 2],
        [1, 2, 0]]], dtype=int64)

In [44]:
np.argsort(b,axis=0)

array([[[0, 0, 0],
        [0, 0, 0]]], dtype=int64)

In [45]:
np.argsort(b,axis=1)

array([[[0, 0, 1],
        [1, 1, 0]]], dtype=int64)

In [46]:
np.argmax(b)

2

In [47]:
np.argmin(b)

1