## NUMPY

### NoNZero

In [4]:
import numpy as np

In [6]:
a=np.array([0,1,2,0,4,5,6])
np.nonzero(a)

(array([1, 2, 4, 5, 6], dtype=int64),)

In [8]:
b=np.array([[3,0,0],[0,4,0],[5,0,0]])    # 0 1 2 row       0 1 0 index respect to aray
np.nonzero(b)

(array([0, 1, 2], dtype=int64), array([0, 1, 0], dtype=int64))

In [10]:
c=np.array([[[1,0,0],[0,2,0],[0,0,3]]])
np.nonzero(c)

(array([0, 0, 0], dtype=int64),
 array([0, 1, 2], dtype=int64),
 array([0, 1, 2], dtype=int64))

### outer

In [12]:
a=np.array([2,4,6])    # 1st array each elemnt multiply with 2nd array all elements
b=np.array([4,2,3])
np.outer(a,b)

array([[ 8,  4,  6],
       [16,  8, 12],
       [24, 12, 18]])

In [16]:
np.ones((5,))

array([1., 1., 1., 1., 1.])

In [14]:
np.linspace(-2,2,5)

array([-2., -1.,  0.,  1.,  2.])

In [17]:
np.outer(np.ones((5,)),np.linspace(-2,2,5))

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

## product

In [23]:
a=np.array([1,2,3])
np.prod(a)

6

In [26]:
b=np.array([[1,2,3],[4,5,6]])
np.prod(b)

720

## sort

In [28]:
a=np.array([[1,4,2],[3,9,4]])
np.sort(a)

array([[1, 2, 4],
       [3, 4, 9]])

In [32]:
sorted(a)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


## standard deviation

In [34]:
x=np.array([1,3,4,5])
np.std(x)

1.479019945774904

In [36]:
a=np.array([[1,3],[4,5]])
print(a)
np.std(a)

[[1 3]
 [4 5]]


1.479019945774904

In [38]:
np.std(a,axis=0)

array([1.5, 1. ])

In [40]:
np.std(a,axis=1)

array([1. , 0.5])

## sum

In [42]:
np.sum([0.5,2])

2.5

In [44]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
np.sum(a)

55

In [46]:
np.sum(a,axis=0)

array([ 7,  9, 11, 13, 15])

In [48]:
np.sum(a,axis=1)

array([15, 40])

## Trace

In [50]:
a=np.arange(1,5).reshape(2,2)
print(a)
np.trace(a)

[[1 2]
 [3 4]]


5

In [52]:
np.trace(np.eye(6))

6.0

In [5]:
import numpy as np
x=np.arange(16).reshape(4,4)
print(x)
np.trace(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


30

In [6]:
x=np.arange(16).reshape(2,8)
print(x)
np.trace(x)  # trace start from 1st elmnt always , either array perfect array or not

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


9

In [7]:
x=np.arange(16).reshape(8,2)
print(x)
np.trace(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


3

In [30]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)
c.trace(2)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([7, 8, 9])

In [40]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]
           ]])
print(c)
c.trace()

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


array([14, 16, 18])

In [32]:
c = np.arange(12).reshape(3,2,2)
c

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [39]:
c.trace(0)

array([6, 8])

## transpose

In [59]:
x=np.arange(1,5).reshape(2,2)
x

array([[1, 2],
       [3, 4]])

In [61]:
np.transpose(x)

array([[1, 3],
       [2, 4]])

In [63]:
x.T

array([[1, 3],
       [2, 4]])

In [44]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c,"\n")
print("transpose",np.transpose(c))
c.T

[[[1 2 3]
  [4 5 6]
  [7 8 9]]] 

transpose [[[1]
  [4]
  [7]]

 [[2]
  [5]
  [8]]

 [[3]
  [6]
  [9]]]


array([[[1],
        [4],
        [7]],

       [[2],
        [5],
        [8]],

       [[3],
        [6],
        [9]]])

## variance

In [73]:
a=np.array([[1,2],[3,4]])
np.var(a)

1.25

In [75]:
np.var(a,axis=0)

array([1., 1.])

In [77]:
np.var(a,axis=1)

array([0.25, 0.25])

# vactrization

In [79]:
def myfun(a,b):
    " return a-b if a>b, otherwise return a+b"
    if a>b:
        return a-b
    else:
        return a+b


In [83]:
vfun=np.vectorize(myfun)
print(vfun.__doc__)

 return a-b if a>b, otherwise return a+b


In [85]:
vfun([1,2,3,4],2)

array([3, 4, 1, 2])

In [87]:
vfun(2,[1,2,3,4,5])

array([1, 4, 5, 6, 7])

In [90]:
vfun([1,2,3],[5,1,9])

array([ 6,  1, 12])

## where

In [92]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
b=np.where(a<5,a,a*10)    # where conditon true value not change, other value will chage acorrd to the condition
b

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [96]:
for i in b:
    print(i)

0
1
2
3
4
50
60
70
80
90
