## NUMPY

### shape manipulation

In [8]:
import numpy as np
a=np.floor(10*np.random.rand(3,4))
a

array([[3., 7., 9., 7.],
       [2., 7., 0., 0.],
       [2., 6., 5., 3.]])

In [10]:
a.reshape(4,3)    # not change original data means a not change

array([[3., 7., 9.],
       [7., 2., 7.],
       [0., 0., 2.],
       [6., 5., 3.]])

In [12]:
a                # a is not changed by reshape , we got original data

array([[3., 7., 9., 7.],
       [2., 7., 0., 0.],
       [2., 6., 5., 3.]])

In [32]:
a.shape

(3, 4)

In [33]:
a.shape=4,3         # a is changed means shape effect the oroginal data
a

array([[3., 7., 9.],
       [7., 2., 7.],
       [0., 0., 2.],
       [6., 5., 3.]])

In [42]:
a.resize(2,2,3)    # change the original data
a

array([[[3., 7., 9.],
        [7., 2., 7.]],

       [[0., 0., 2.],
        [6., 5., 3.]]])

In [40]:
a.ravel()                           # ravle convert multidimension into vector means 1d array  # value are same as original

array([3., 7., 9., 7., 2., 7., 0., 0., 2., 6., 5., 3.])

In [44]:
a.flatten()                        # same as ravel

array([3., 7., 9., 7., 2., 7., 0., 0., 2., 6., 5., 3.])

In [45]:
a

array([[[3., 7., 9.],
        [7., 2., 7.]],

       [[0., 0., 2.],
        [6., 5., 3.]]])

In [50]:
c=a.reshape(6,2)        # returns the array with a modified shape
c

array([[3., 7.],
       [9., 7.],
       [2., 7.],
       [0., 0.],
       [2., 6.],
       [5., 3.]])

In [47]:
a

array([[[3., 7., 9.],
        [7., 2., 7.]],

       [[0., 0., 2.],
        [6., 5., 3.]]])

In [34]:
a.T   
a                    # transpose also changed original data

array([[3., 7., 9.],
       [7., 2., 7.],
       [0., 0., 2.],
       [6., 5., 3.]])

In [35]:
a.transpose()

array([[3., 7., 0., 6.],
       [7., 2., 0., 5.],
       [9., 7., 2., 3.]])

In [21]:
a.T.shape

(4, 3)

## flatten

In [52]:
a

array([[[3., 7., 9.],
        [7., 2., 7.]],

       [[0., 0., 2.],
        [6., 5., 3.]]])

In [56]:
a=np.array([[1,2],[3,4]])
print(a)
a.ndim

[[1 2]
 [3 4]]


2

In [58]:
a.flatten()

array([1, 2, 3, 4])

## TANSPOSE LIKE OPERAOTR

In [68]:
a=np.zeros([3,4,5])
a

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [70]:
a.shape

(3, 4, 5)

In [96]:
np.moveaxis(a,0,-1).shape  # 0 axis move to -1 , -1 to -2 ,-2 to -3

(2, 2)

In [97]:
np.moveaxis(a,0,-2).shape   ##  ????

(2, 2)

In [98]:
np.transpose(a).shape

(2, 2)

In [99]:
np.swapaxes(a,0,1).shape

(2, 2)

## stacking togetger diff array

In [100]:
np.random.random((2,2))

array([[0.66622571, 0.27587876],
       [0.62204362, 0.01202202]])

In [101]:
a=np.floor(10*np.random.random((2,2)))
a

array([[1., 4.],
       [4., 9.]])

In [102]:
b=np.floor(10*np.random.random((2,2)))
b

array([[1., 3.],
       [0., 6.]])

In [106]:
np.vstack((a,b))     # vertical merge both a and b

array([[1., 4.],
       [4., 9.],
       [1., 3.],
       [0., 6.]])

In [107]:
np.hstack((a,b))    # horizental merge both a and b

array([[1., 4., 1., 3.],
       [4., 9., 0., 6.]])

In [109]:
from numpy import newaxis
np.column_stack((a,b))       # with 2D array

array([[1., 4., 1., 3.],
       [4., 9., 0., 6.]])

In [111]:
a=np.array([4,2])          # store each array as column
b=np.array([3,8])
np.column_stack((a,b))     # return 2D array

array([[4, 3],
       [2, 8]])

In [113]:
np.hstack((a,b))     

array([4, 2, 3, 8])

In [116]:
a      # horizental vector

array([4, 2])

In [118]:
a[:,newaxis]     # return 2D array

array([[4],
       [2]])

In [120]:
b[:,newaxis]

array([[3],
       [8]])

In [122]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4, 3],
       [2, 8]])

In [125]:
np.hstack((a[:,newaxis],b[:,newaxis]))   # same  result as column stach

array([[4, 3],
       [2, 8]])

In [133]:
a=[np.random.randn(3,4) for _ in range(5)]
a

[array([[ 0.85565886,  0.46991227,  0.51046598, -0.20485643],
        [ 0.48497635, -0.7591627 ,  0.06575061,  0.404532  ],
        [-0.10075952, -0.81488319,  0.0617682 , -1.63891044]]),
 array([[ 0.55229229, -0.53799901, -0.38140195, -0.60480952],
        [-0.03750373,  0.25927283, -0.28044457,  0.6036618 ],
        [-1.30554132,  0.80839949, -1.52451385, -0.52094464]]),
 array([[ 0.32454171, -0.2186786 ,  1.17656642,  1.25552251],
        [ 0.6595446 , -1.17771478,  0.36321674, -0.47587493],
        [-1.7193157 , -1.66222503, -0.22533295, -0.38717698]]),
 array([[ 0.17459017, -0.41139941,  0.58288619,  0.49212805],
        [-0.95645817,  3.20388608,  1.44592713,  1.92431029],
        [-0.12026888, -0.686585  ,  0.51743387,  0.2755579 ]]),
 array([[ 0.14699581,  1.21553406, -1.84454217, -0.5736652 ],
        [ 0.76364652, -1.14984454, -0.88923432,  0.44263123],
        [-0.99296453,  0.02442961,  0.09830864, -1.19446338]])]

In [134]:
np.stack(a,axis=0).shape

(5, 3, 4)

In [136]:
b=np.stack(a,axis=1)
b

array([[[ 0.85565886,  0.46991227,  0.51046598, -0.20485643],
        [ 0.55229229, -0.53799901, -0.38140195, -0.60480952],
        [ 0.32454171, -0.2186786 ,  1.17656642,  1.25552251],
        [ 0.17459017, -0.41139941,  0.58288619,  0.49212805],
        [ 0.14699581,  1.21553406, -1.84454217, -0.5736652 ]],

       [[ 0.48497635, -0.7591627 ,  0.06575061,  0.404532  ],
        [-0.03750373,  0.25927283, -0.28044457,  0.6036618 ],
        [ 0.6595446 , -1.17771478,  0.36321674, -0.47587493],
        [-0.95645817,  3.20388608,  1.44592713,  1.92431029],
        [ 0.76364652, -1.14984454, -0.88923432,  0.44263123]],

       [[-0.10075952, -0.81488319,  0.0617682 , -1.63891044],
        [-1.30554132,  0.80839949, -1.52451385, -0.52094464],
        [-1.7193157 , -1.66222503, -0.22533295, -0.38717698],
        [-0.12026888, -0.686585  ,  0.51743387,  0.2755579 ],
        [-0.99296453,  0.02442961,  0.09830864, -1.19446338]]])

In [137]:
np.stack(a,axis=1).shape

(3, 5, 4)

In [139]:
np.stack(a,axis=2)

array([[[ 0.85565886,  0.55229229,  0.32454171,  0.17459017,
          0.14699581],
        [ 0.46991227, -0.53799901, -0.2186786 , -0.41139941,
          1.21553406],
        [ 0.51046598, -0.38140195,  1.17656642,  0.58288619,
         -1.84454217],
        [-0.20485643, -0.60480952,  1.25552251,  0.49212805,
         -0.5736652 ]],

       [[ 0.48497635, -0.03750373,  0.6595446 , -0.95645817,
          0.76364652],
        [-0.7591627 ,  0.25927283, -1.17771478,  3.20388608,
         -1.14984454],
        [ 0.06575061, -0.28044457,  0.36321674,  1.44592713,
         -0.88923432],
        [ 0.404532  ,  0.6036618 , -0.47587493,  1.92431029,
          0.44263123]],

       [[-0.10075952, -1.30554132, -1.7193157 , -0.12026888,
         -0.99296453],
        [-0.81488319,  0.80839949, -1.66222503, -0.686585  ,
          0.02442961],
        [ 0.0617682 , -1.52451385, -0.22533295,  0.51743387,
          0.09830864],
        [-1.63891044, -0.52094464, -0.38717698,  0.2755579 ,
         -1

In [141]:
np.stack(a,axis=2).shape

(3, 4, 5)

# depth stack

In [143]:
a=np.array((1,2,3))
b=np.array((2,3,4))
np.dstack((a,b))

array([[[1, 2],
        [2, 3],
        [3, 4]]])

In [144]:
a=np.array([[1],[2],[3]])
b=np.array([[2],[3],[4]])
np.dstack((a,b))

array([[[1, 2]],

       [[2, 3]],

       [[3, 4]]])