## Copy and View

In [3]:
import numpy as np

### no copy at ALL

## Normal Copy

In [4]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
b=a       # "a" given refrence of the item stored in the a to b,  so both have a same memory address for array
b is a    # True bcoz both have the same memory location for array
## print(a.data)
## print(b.data)   # both memory address r same

True

In [11]:
# try other example with same value but memory address not same
c=[1,2,3]
d=[1,2,3]   
c is d  # false bcoz this is looking same but memory address is diffrent  # bcoz we have not copy the address or refrence or c array

False

In [12]:
b.shape

(12,)

In [14]:
b.shape=3,2,2   # split into 3 array with 2 row n 2 column each
b

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [15]:
a             # here see our a value is also changed now a is

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [22]:
b.reshape(2,2,3)      # we reshape b but we know reshape not effect the orignal data

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [23]:
b                   # ur b is same as not effected by Reshape

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [24]:
a                  # a is also same not changed by Reshape

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

#### now we make chnges into array

In [43]:
b[0]=10,20    # assign new value then effect the original data
b             # now our original data is effected n changed  # "b" is changed its also effect "a"

array([[[10, 20],
        [10, 20]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [44]:
a                    # see "a" data is changed bcoz we do changes into "b" bcoz normal copy

array([[[10, 20],
        [10, 20]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [28]:
a[0,:]

array([[0, 1],
       [2, 3]])

## View or Shallow Copy

##### A shallow copy means constructing a new collection object and then populating it with references to the child objects
##### found in the original. 

In [47]:
c=a.view()   # here c take the refrence of array "a", so both c and a have same value
print(a.data)
print(c.data)

In [48]:
c

array([[[10, 20],
        [10, 20]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [52]:
c[0]=25     # effect the original data this changes also made in "a" and "b" both r chnaged
c

array([[[25, 25],
        [25, 25]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [54]:
a                              # original data changed

array([[[25, 25],
        [25, 25]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [53]:
b                               # original data changed

array([[[25, 25],
        [25, 25]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [54]:
s=a[:,1:3]      # indexing n slicing both
s

array([[[25, 25]],

       [[ 6,  7]],

       [[10, 11]]])

In [56]:
s[:]=100      # assign value or make chnges
a             # effect all the original data

array([[[ 25,  25],
        [100, 100]],

       [[  4,   5],
        [100, 100]],

       [[  8,   9],
        [100, 100]]])

In [59]:
a   # all effected

array([[[ 25,  25],
        [100, 100]],

       [[  4,   5],
        [100, 100]],

       [[  8,   9],
        [100, 100]]])

In [60]:
b   # effected

array([[[ 25,  25],
        [100, 100]],

       [[  4,   5],
        [100, 100]],

       [[  8,   9],
        [100, 100]]])

In [62]:
c    # effected

array([[[ 25,  25],
        [100, 100]],

       [[  4,   5],
        [100, 100]],

       [[  8,   9],
        [100, 100]]])

## deep copy

##### A deep copy makes the copying process recursive. It means first constructing a new collection object and
##### then recursively populating it with copies of the child objects found in the original

In [63]:
# deep copy create
d=a.copy()   # not effect the orignal data
d

array([[[ 25,  25],
        [100, 100]],

       [[  4,   5],
        [100, 100]],

       [[  8,   9],
        [100, 100]]])

In [64]:
d is a

False

In [65]:
d.base is a

False

In [66]:
a                # original data

array([[[ 25,  25],
        [100, 100]],

       [[  4,   5],
        [100, 100]],

       [[  8,   9],
        [100, 100]]])

In [73]:
d[0,0]=999    # make chnges into "d" array
d

array([[[999, 999],
        [100, 100]],

       [[  4,   5],
        [100, 100]],

       [[  8,   9],
        [100, 100]]])

In [67]:
a        # "a" original data not effected

array([[[ 25,  25],
        [100, 100]],

       [[  4,   5],
        [100, 100]],

       [[  8,   9],
        [100, 100]]])

## conversion

In [72]:
a=np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [73]:
a.ndim

1

In [74]:
a.astype(np.complex)   # we convert integer into complex   # complex python data type

array([ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,
        7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j,
       14.+0.j, 15.+0.j, 16.+0.j, 17.+0.j, 18.+0.j, 19.+0.j])

In [75]:
a.astype(np.complex128)            # complex128 Numpy data type

array([ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,
        7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j,
       14.+0.j, 15.+0.j, 16.+0.j, 17.+0.j, 18.+0.j, 19.+0.j])

In [76]:
c=np.atleast_2d(a)          # convert 1D array into 2D array
print(c)
print(c.shape)             # 1 row 20 columns

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]
(1, 20)


In [77]:
d=np.atleast_3d(a)        # convert 1D array into 3D array
print(d)
d.shape                  # 1 array with 20 rows n 1 column

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]
  [13]
  [14]
  [15]
  [16]
  [17]
  [18]
  [19]]]


(1, 20, 1)

In [78]:
c=np.ravel(d)     # convert array into 1D array or vector
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [79]:
c.ndim

1

In [80]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [97]:
e=np.mat(a)   # convert array or vector into matrix or 2D array  # mat=>matrix
e

matrix([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19]])

In [100]:
np.asmatrix(a)     # convert array or vector into matrix or 2D array

matrix([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19]])

In [102]:
np.asarray(e)   # convert matrix "e" into array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [85]:
f=10     # scalar
j=np.asarray(f)    # also convert scalar into array
j

array(10)

In [86]:
j.ndim   # bcoz scalar

0

In [87]:
j.shape    # bcoz scalar

()

In [90]:
k=np.asmatrix(f)    # convert scalar into matrix or 2D matrix
k

matrix([[10]])

In [92]:
k.ndim

2

In [94]:
k.shape

(1, 1)