## NUMPY array manipulation

In [1]:
import numpy as np

In [6]:
# This is used to concatenate any number of array slices along row (first) axis
np.r_[1:4,0,4]      # concatenate element into row  # 1 to 3 bydefault value array we add only 0,4 so add at last but in a row manner

array([1, 2, 3, 0, 4])

In [8]:
# this is used for concatenate element into array as a column wise
np.c_[np.array([1,2,3]),np.array([4,5,6])]  # concatenate both array as column wise [1,2,3] 1St column, [4,5,6] 2nd column
                                            # return 2D array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [12]:
np.c_[np.array([1,2,3]),np.array([4,5,6]),np.array([7,8,9])]   # for 3rd array add as a 3rd column  # Return 2D array

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [5]:
a=np.c_[np.array([[1,2,3]]),0,0,0,np.array([[4,5,6]])]   # its 2d ARRAY SO 
a

array([[1, 2, 3, 0, 0, 0, 4, 5, 6]])

In [18]:
a.ndim

2

In [20]:
a.shape

(1, 9)

## split

In [26]:

x=np.arange(16.0).reshape(4,4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [28]:
# verticaly split the array # if has 4 rows then 0,1 row 1st array , 2,3 rows 2nd array
np.vsplit(x,2)    # divide X into 2 array

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [30]:
np.vsplit(x,np.array([3,4]))     # divide X into 3 array , each has 4 column

[array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[12., 13., 14., 15.]]),
 array([], shape=(0, 4), dtype=float64)]

### Hstack or Hsplit

In [33]:
# horizentaly split the array  # if has 4 column then 0,1 col as 1st array,  2,3 col as a 2nd arrray
np.hsplit(x,2)    # 2 array horizental like horizental Stack

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]), array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

# dsplit 

In [35]:
y=np.arange(24).reshape(2,2,6)
y

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [37]:
np.dsplit(y,3)

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]), array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]), array([[[ 4,  5],
         [10, 11]],
 
        [[16, 17],
         [22, 23]]])]

In [7]:
x=np.arange(16.0)
np.array_split(x,4)   # array split into 4 array as row wsie

[array([0., 1., 2., 3.]),
 array([4., 5., 6., 7.]),
 array([ 8.,  9., 10., 11.]),
 array([12., 13., 14., 15.])]

In [9]:
np.split(x,8)    # array split into 8 array   # 2 elements in each bcoz of equal distribution of 16 items

[array([0., 1.]),
 array([2., 3.]),
 array([4., 5.]),
 array([6., 7.]),
 array([8., 9.]),
 array([10., 11.]),
 array([12., 13.]),
 array([14., 15.])]