In [1]:
import numpy as np

## broadcasting rule

In [2]:
x=np.arange(4)     # vector
xx=x.reshape(4,1)  # 2D array
y=np.ones(5)       # vector
z=np.ones((3,4))   # 2D array
print(x)
print(xx)
print(y)
print(z)

[0 1 2 3]
[[0]
 [1]
 [2]
 [3]]
[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
x.shape    # vector so (4,) shape given only no of elemnts

(4,)

In [4]:
xx.shape

(4, 1)

In [5]:
y.shape

(5,)

In [6]:
z.shape

(3, 4)

In [7]:
x+y

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [8]:
(xx+y).shape

(4, 5)

In [9]:
xx+y

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [10]:
x+z

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [11]:
(x+z).shape

(3, 4)

## automatic reshapeing  [ (only work in reshape)  -negative indexing  ]

In [12]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
a.reshape(4,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
a.reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
a.reshape(-1,1)    # we specify conly coumn so 1 means all the element in 1 column

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [16]:
a.reshape(1,-1)      # we specify 1 row n all the elemnts in 1 row

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [17]:
a.resize(4,-1)        # minus indexing not working in " RESIZE"

ValueError: negative dimensions not allowed

In [18]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
x.reshape(10,20)   # bcoz not enough element

ValueError: cannot reshape array of size 4 into shape (10,20)

In [20]:
a.reshape(4,-1).shape

(4, 3)

In [21]:
a.reshape(4,-2).shape

(4, 3)

In [22]:
a.reshape(4,-100).shape

(4, 3)

In [23]:
a.reshape(-1,3).shape

(4, 3)

## matrix

In [24]:
a=np.matrix('1,2;3,4')
print(a)    # print give u the list of elemnts

[[1 2]
 [3 4]]


In [25]:
a    # a give u wich type of data structure with list of elemnts too

matrix([[1, 2],
        [3, 4]])

In [26]:
a.shape

(2, 2)

In [27]:
a.ndim

2

In [28]:
b=np.matrix([[1,2],[3,4]])
b

matrix([[1, 2],
        [3, 4]])

In [29]:
b.shape

(2, 2)

In [30]:
b.ndim

2

In [31]:
np.dot(a,b)

matrix([[ 7, 10],
        [15, 22]])

In [32]:
a@b                 # @ also used for dot product of matrix

matrix([[ 7, 10],
        [15, 22]])

In [33]:
np.add(a,b)

matrix([[2, 4],
        [6, 8]])

In [34]:
a.dtype

dtype('int32')

In [35]:
b.dtype

dtype('int32')

In [36]:
np.multiply(a,b)

matrix([[ 1,  4],
        [ 9, 16]])

In [37]:
np.subtract(a,b)

matrix([[0, 0],
        [0, 0]])

In [38]:
np.mean(a)

2.5

In [39]:
np.mean(a+b)

5.0

In [40]:
np.mean(b)

2.5

In [41]:
np.max(a)


4

In [42]:
np.min(b)

1

In [43]:
mx=np.matrix(np.arange(12)).reshape(4,3)
mx

matrix([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [44]:
mx[0]

matrix([[0, 1, 2]])

In [45]:
mx[0:2]

matrix([[0, 1, 2],
        [3, 4, 5]])

In [46]:
i=[1,2]

In [47]:
mx[i]     # ************ matrix is easy to manipulateor execute over array

matrix([[3, 4, 5],
        [6, 7, 8]])

# xarray

## Pytorch 1. 0 . 2

## tensorflow 1.15.0   python 3.6